name: quantecon
channels:
  - default
  - conda-forge
dependencies:
  - python=3.11
  - anaconda=2024.02
  - pip
  - pip:
    - jupyter-book==0.15.1
    - docutils==0.17.1
    - quantecon-book-theme==0.7.1
    - sphinx-tojupyter==0.3.0
    - sphinxext-rediraffe==0.2.7
    - sphinx-exercise==0.4.1
    - git+https://github.com/executablebooks/sphinx-proof@main
    - ghp-import==1.1.0
    - sphinxcontrib-youtube==1.1.0
    - sphinx-togglebutton==0.3.1
    # Sandpit Requirements
    # - PuLP
    # - cvxpy
    # - cvxopt
    # - cylp
    # - array-to-latex
    # - prettytable
